airports:
    type:     rest
    resource: Bsegal\TravelApiBundle\Controller\AirportController

flights:
    type:     rest
    resource: Bsegal\TravelApiBundle\Controller\FlightController

trips:
    type:     rest
    resource: Bsegal\TravelApiBundle\Controller\TripController

passengers:
    type:     rest
    resource: Bsegal\TravelApiBundle\Controller\PassengerController